(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.bag_1__code.

#[global] Opaque bag_1٠create.
#[global] Opaque bag_1٠push₁.
#[global] Opaque bag_1٠push.
#[global] Opaque bag_1٠pop₁.
#[global] Opaque bag_1٠pop.
