(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.bag_2__code.

#[global] Opaque bag_2٠create.
#[global] Opaque bag_2٠add_producer₁.
#[global] Opaque bag_2٠add_producer.
#[global] Opaque bag_2٠create_producer.
#[global] Opaque bag_2٠close_producer.
#[global] Opaque bag_2٠create_consumer.
#[global] Opaque bag_2٠push.
#[global] Opaque bag_2٠pop₂.
#[global] Opaque bag_2٠pop₁.
#[global] Opaque bag_2٠pop.
