(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export backoff.backoff.
Require Import zoo.options.

Notation "'Null'" := (
  in_type "zoo_saturn.bqueue_mpmc.node" Tag0
)(in custom zoo_tag
).
Notation "'Node'" := (
  in_type "zoo_saturn.bqueue_mpmc.node" Tag1
)(in custom zoo_tag
).

Notation "'next'" := (
  in_type "zoo_saturn.bqueue_mpmc.node.Node" 0
)(in custom zoo_field
).
Notation "'data'" := (
  in_type "zoo_saturn.bqueue_mpmc.node.Node" 1
)(in custom zoo_field
).
Notation "'index'" := (
  in_type "zoo_saturn.bqueue_mpmc.node.Node" 2
)(in custom zoo_field
).
Notation "'estimated_capacity'" := (
  in_type "zoo_saturn.bqueue_mpmc.node.Node" 3
)(in custom zoo_field
).

Notation "'capacity'" := (
  in_type "zoo_saturn.bqueue_mpmc.t" 0
)(in custom zoo_field
).
Notation "'front'" := (
  in_type "zoo_saturn.bqueue_mpmc.t" 1
)(in custom zoo_field
).
Notation "'back'" := (
  in_type "zoo_saturn.bqueue_mpmc.t" 2
)(in custom zoo_field
).
