(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export backoff.backoff.
Require Import zoo.options.

Notation "'Nil'" := (
  in_type "zoo_saturn.bstack_mpmc.list" 0
)(in custom zoo_tag
).
Notation "'Cons'" := (
  in_type "zoo_saturn.bstack_mpmc.list" 1
)(in custom zoo_tag
).

Notation "'capacity'" := (
  in_type "zoo_saturn.bstack_mpmc.t" 0
)(in custom zoo_field
).
Notation "'front'" := (
  in_type "zoo_saturn.bstack_mpmc.t" 1
)(in custom zoo_field
).
