(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.bstack_mpmc__code.

#[global] Opaque bstack_mpmc٠create.
#[global] Opaque bstack_mpmc٠size.
#[global] Opaque bstack_mpmc٠is_empty.
#[global] Opaque bstack_mpmc٠push_aux.
#[global] Opaque bstack_mpmc٠push₁.
#[global] Opaque bstack_mpmc٠push.
#[global] Opaque bstack_mpmc٠pop₁.
#[global] Opaque bstack_mpmc٠pop.
