(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_saturn.channel_sync_1.
Require Import zoo_std.array.
Require Import zoo_std.random.
Require Import zoo.options.

Notation "'channel_sync_2٠channels'" := (
  in_type "zoo_saturn.channel_sync_2.t" 0
)(in custom zoo_proj
).
Notation "'channel_sync_2٠capacity_log'" := (
  in_type "zoo_saturn.channel_sync_2.t" 1
)(in custom zoo_proj
).

Definition channel_sync_2٠create : val :=
  𝗳𝘂𝗻 "cap_log" ->
    ( array٠unsafe_init (1 𝗹𝘀𝗹 "cap_log") channel_sync_1٠create, "cap_log" ).

Definition channel_sync_2٠send₁ : val :=
  𝗿𝗲𝗰 "send" "t" "v" "log" ->
    𝗶𝗳 "t".<channel_sync_2٠capacity_log> < "log" 𝘁𝗵𝗲𝗻 (
      false
    ) 𝗲𝗹𝘀𝗲 (
      𝗹𝗲𝘁 "i" = random٠int (1 𝗹𝘀𝗹 "log") 𝗶𝗻
      𝗹𝗲𝘁 "chan" = array٠unsafe_get "t".<channel_sync_2٠channels> "i" 𝗶𝗻
      channel_sync_1٠send "chan" "v" 𝗼𝗿 "send" "t" "v" ("log" + 1)
    ).

Definition channel_sync_2٠send : val :=
  𝗳𝘂𝗻 "t" "v" ->
    channel_sync_2٠send₁ "t" "v" 0.

Definition channel_sync_2٠recv₁ : val :=
  𝗿𝗲𝗰 "recv" "t" "log" ->
    𝗶𝗳 "t".<channel_sync_2٠capacity_log> < "log" 𝘁𝗵𝗲𝗻 (
      §None
    ) 𝗲𝗹𝘀𝗲 (
      𝗹𝗲𝘁 "i" = random٠int (1 𝗹𝘀𝗹 "log") 𝗶𝗻
      𝗹𝗲𝘁 "chan" = array٠unsafe_get "t".<channel_sync_2٠channels> "i" 𝗶𝗻
      𝗺𝗮𝘁𝗰𝗵 channel_sync_1٠recv "chan" 𝘄𝗶𝘁𝗵
      | None ->
          "recv" "t" ("log" + 1)
      | Some ⎽ 𝗮𝘀 "res" ->
          "res"
      𝗲𝗻𝗱
    ).

Definition channel_sync_2٠recv : val :=
  𝗳𝘂𝗻 "t" ->
    channel_sync_2٠recv₁ "t" 0.
