(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.channel_sync_1__code.

#[global] Opaque channel_sync_1٠create.
#[global] Opaque channel_sync_1٠send.
#[global] Opaque channel_sync_1٠send_aux.
#[global] Opaque channel_sync_1٠recv.
#[global] Opaque channel_sync_1٠recv_aux.
