(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_saturn.channel_sync_1.
Require Export zoo_std.array.
Require Export zoo_std.random.
Require Import zoo.options.

Notation "'channels'" := (
  in_type "zoo_saturn.channel_sync_2.t" 0
)(in custom zoo_proj
).
Notation "'capacity_log'" := (
  in_type "zoo_saturn.channel_sync_2.t" 1
)(in custom zoo_proj
).
