(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_std.domain.
Require Import zoo.options.

Notation "'channel_sync_1٠Null'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag0
)(in custom zoo_tag
).
Notation "'channel_sync_1٠Sender_offer'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag1
)(in custom zoo_tag
).
Notation "'channel_sync_1٠Sender_accept'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag2
)(in custom zoo_tag
).
Notation "'channel_sync_1٠Receiver_offer'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag3
)(in custom zoo_tag
).
Notation "'channel_sync_1٠Receiver_accept'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag4
)(in custom zoo_tag
).

Definition channel_sync_1٠create : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗿𝗲𝗳 §channel_sync_1٠Null.

#[local] Definition __zoo_recs_0 :=
  ( 𝗿𝗲𝗰𝘀 "send" "t" "v" ->
      𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
      | channel_sync_1٠Null ->
          "send_aux" "t" "v"
      | channel_sync_1٠Receiver_offer ->
          𝗰𝗮𝘀
            "t".[contents]
            §channel_sync_1٠Receiver_offer
            ‘channel_sync_1٠Sender_accept[ "v" ]
      |⎽ ->
          false
      𝗲𝗻𝗱
    𝘄𝗶𝘁𝗵 "send_aux" "t" "v" ->
      𝗶𝗳
        𝗰𝗮𝘀
          "t".[contents]
          §channel_sync_1٠Null
          ‘channel_sync_1٠Sender_offer[ "v" ]
      𝘁𝗵𝗲𝗻 (
        domain٠yield () ⍮
        𝗺𝗮𝘁𝗰𝗵 𝘅𝗰𝗵𝗴 "t".[contents] §channel_sync_1٠Null 𝘄𝗶𝘁𝗵
        | channel_sync_1٠Sender_offer ⎽ ->
            false
        | channel_sync_1٠Receiver_accept ->
            true
        |⎽ ->
            𝗳𝗮𝗶𝗹
        𝗲𝗻𝗱
      ) 𝗲𝗹𝘀𝗲 (
        "send" "t" "v"
      )
  )%zoo_recs.
Definition channel_sync_1٠send :=
  ValRecs 0 __zoo_recs_0.
Definition channel_sync_1٠send_aux :=
  ValRecs 1 __zoo_recs_0.
#[global] Instance :
  AsValRecs' channel_sync_1٠send 0 __zoo_recs_0 [
    channel_sync_1٠send ;
    channel_sync_1٠send_aux
  ].
Proof.
  done.
Qed.
#[global] Instance :
  AsValRecs' channel_sync_1٠send_aux 1 __zoo_recs_0 [
    channel_sync_1٠send ;
    channel_sync_1٠send_aux
  ].
Proof.
  done.
Qed.

#[local] Definition __zoo_recs_1 :=
  ( 𝗿𝗲𝗰𝘀 "recv" "t" ->
      𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
      | channel_sync_1٠Null ->
          "recv_aux" "t"
      | channel_sync_1٠Sender_offer "v" 𝗮𝘀 "state" ->
          𝗶𝗳
            𝗰𝗮𝘀 "t".[contents] "state" §channel_sync_1٠Receiver_accept
          𝘁𝗵𝗲𝗻 (
            ‘Some( "v" )
          ) 𝗲𝗹𝘀𝗲 (
            §None
          )
      |⎽ ->
          §None
      𝗲𝗻𝗱
    𝘄𝗶𝘁𝗵 "recv_aux" "t" ->
      𝗶𝗳
        𝗰𝗮𝘀
          "t".[contents]
          §channel_sync_1٠Null
          §channel_sync_1٠Receiver_offer
      𝘁𝗵𝗲𝗻 (
        domain٠yield () ⍮
        𝗺𝗮𝘁𝗰𝗵 𝘅𝗰𝗵𝗴 "t".[contents] §channel_sync_1٠Null 𝘄𝗶𝘁𝗵
        | channel_sync_1٠Receiver_offer ->
            §None
        | channel_sync_1٠Sender_accept "v" ->
            ‘Some( "v" )
        |⎽ ->
            𝗳𝗮𝗶𝗹
        𝗲𝗻𝗱
      ) 𝗲𝗹𝘀𝗲 (
        "recv" "t"
      )
  )%zoo_recs.
Definition channel_sync_1٠recv :=
  ValRecs 0 __zoo_recs_1.
Definition channel_sync_1٠recv_aux :=
  ValRecs 1 __zoo_recs_1.
#[global] Instance :
  AsValRecs' channel_sync_1٠recv 0 __zoo_recs_1 [
    channel_sync_1٠recv ;
    channel_sync_1٠recv_aux
  ].
Proof.
  done.
Qed.
#[global] Instance :
  AsValRecs' channel_sync_1٠recv_aux 1 __zoo_recs_1 [
    channel_sync_1٠recv ;
    channel_sync_1٠recv_aux
  ].
Proof.
  done.
Qed.
