(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_std.domain.
Require Import zoo.options.

Notation "'Null'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag0
)(in custom zoo_tag
).
Notation "'Sender_offer'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag1
)(in custom zoo_tag
).
Notation "'Sender_accept'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag2
)(in custom zoo_tag
).
Notation "'Receiver_offer'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag3
)(in custom zoo_tag
).
Notation "'Receiver_accept'" := (
  in_type "zoo_saturn.channel_sync_1.state" Tag4
)(in custom zoo_tag
).
