(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_std.domain.
Require Import zoo.options.

Notation "'exchanger_1٠Null'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag0
)(in custom zoo_tag
).
Notation "'exchanger_1٠Offer'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag1
)(in custom zoo_tag
).
Notation "'exchanger_1٠Accept'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag2
)(in custom zoo_tag
).

Definition exchanger_1٠create : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗿𝗲𝗳 §exchanger_1٠Null.

#[local] Definition __zoo_recs_0 :=
  ( 𝗿𝗲𝗰𝘀 "exchange" "t" "v" ->
      𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
      | exchanger_1٠Null ->
          "exchange_aux" "t" "v"
      | exchanger_1٠Offer "w" 𝗮𝘀 "state" ->
          𝗶𝗳 𝗰𝗮𝘀 "t".[contents] "state" ‘exchanger_1٠Accept[ "v" ] 𝘁𝗵𝗲𝗻 (
            ‘Some( "w" )
          ) 𝗲𝗹𝘀𝗲 (
            §None
          )
      | exchanger_1٠Accept ⎽ ->
          §None
      𝗲𝗻𝗱
    𝘄𝗶𝘁𝗵 "exchange_aux" "t" "v" ->
      𝗶𝗳
        𝗰𝗮𝘀 "t".[contents] §exchanger_1٠Null ‘exchanger_1٠Offer[ "v" ]
      𝘁𝗵𝗲𝗻 (
        domain٠yield () ⍮
        𝗺𝗮𝘁𝗰𝗵 𝘅𝗰𝗵𝗴 "t".[contents] §exchanger_1٠Null 𝘄𝗶𝘁𝗵
        | exchanger_1٠Null ->
            𝗳𝗮𝗶𝗹
        | exchanger_1٠Offer ⎽ ->
            §None
        | exchanger_1٠Accept "w" ->
            ‘Some( "w" )
        𝗲𝗻𝗱
      ) 𝗲𝗹𝘀𝗲 (
        "exchange" "t" "v"
      )
  )%zoo_recs.
Definition exchanger_1٠exchange :=
  ValRecs 0 __zoo_recs_0.
Definition exchanger_1٠exchange_aux :=
  ValRecs 1 __zoo_recs_0.
#[global] Instance :
  AsValRecs' exchanger_1٠exchange 0 __zoo_recs_0 [
    exchanger_1٠exchange ;
    exchanger_1٠exchange_aux
  ].
Proof.
  done.
Qed.
#[global] Instance :
  AsValRecs' exchanger_1٠exchange_aux 1 __zoo_recs_0 [
    exchanger_1٠exchange ;
    exchanger_1٠exchange_aux
  ].
Proof.
  done.
Qed.
