(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.exchanger_1__code.

#[global] Opaque exchanger_1٠create.
#[global] Opaque exchanger_1٠exchange.
#[global] Opaque exchanger_1٠exchange_aux.
