(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_std.domain.
Require Import zoo.options.

Notation "'Null'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag0
)(in custom zoo_tag
).
Notation "'Offer'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag1
)(in custom zoo_tag
).
Notation "'Accept'" := (
  in_type "zoo_saturn.exchanger_1.state" Tag2
)(in custom zoo_tag
).
