(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_saturn.exchanger_1.
Require Import zoo_std.array.
Require Import zoo_std.random.
Require Import zoo.options.

Notation "'exchanger_2٠exchangers'" := (
  in_type "zoo_saturn.exchanger_2.t" 0
)(in custom zoo_proj
).
Notation "'exchanger_2٠capacity_log'" := (
  in_type "zoo_saturn.exchanger_2.t" 1
)(in custom zoo_proj
).

Definition exchanger_2٠create : val :=
  𝗳𝘂𝗻 "cap_log" ->
    ( array٠unsafe_init (1 𝗹𝘀𝗹 "cap_log") exchanger_1٠create, "cap_log" ).

Definition exchanger_2٠random_exchanger : val :=
  𝗳𝘂𝗻 "t" "log" ->
    𝗹𝗲𝘁 "i" = random٠int (1 𝗹𝘀𝗹 "log") 𝗶𝗻
    array٠unsafe_get "t".<exchanger_2٠exchangers> "i".

Definition exchanger_2٠exchange₁ : val :=
  𝗿𝗲𝗰 "exchange" "t" "v" "log" ->
    𝗶𝗳 "t".<exchanger_2٠capacity_log> < "log" 𝘁𝗵𝗲𝗻 (
      §None
    ) 𝗲𝗹𝘀𝗲 (
      𝗹𝗲𝘁 "exchanger" = exchanger_2٠random_exchanger "t" "log" 𝗶𝗻
      𝗺𝗮𝘁𝗰𝗵 exchanger_1٠exchange "exchanger" "v" 𝘄𝗶𝘁𝗵
      | None ->
          "exchange" "t" "v" ("log" + 1)
      | Some ⎽ 𝗮𝘀 "res" ->
          "res"
      𝗲𝗻𝗱
    ).

Definition exchanger_2٠exchange : val :=
  𝗳𝘂𝗻 "t" "v" ->
    exchanger_2٠exchange₁ "t" "v" 0.
