(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.inf_ws_deque_2__code.

#[global] Opaque inf_ws_deque_2٠create.
#[global] Opaque inf_ws_deque_2٠size.
#[global] Opaque inf_ws_deque_2٠is_empty.
#[global] Opaque inf_ws_deque_2٠push.
#[global] Opaque inf_ws_deque_2٠steal.
#[global] Opaque inf_ws_deque_2٠pop.
