(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.queue_mpmc_1__code.

#[global] Opaque queue_mpmc_1٠create.
#[global] Opaque queue_mpmc_1٠is_empty.
#[global] Opaque queue_mpmc_1٠push₂.
#[global] Opaque queue_mpmc_1٠push₁.
#[global] Opaque queue_mpmc_1٠fix_back₁.
#[global] Opaque queue_mpmc_1٠fix_back.
#[global] Opaque queue_mpmc_1٠push.
#[global] Opaque queue_mpmc_1٠pop₁.
#[global] Opaque queue_mpmc_1٠pop.
