(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export backoff.backoff.
Require Import zoo.options.

Notation "'Front'" := (
  in_type "zoo_saturn.queue_mpmc_2.suffix" Tag0
)(in custom zoo_tag
).
Notation "'Cons'" := (
  in_type "zoo_saturn.queue_mpmc_2.suffix" Tag1
)(in custom zoo_tag
).

Notation "'Back'" := (
  in_type "zoo_saturn.queue_mpmc_2.prefix" Tag0
)(in custom zoo_tag
).
Notation "'Snoc'" := (
  in_type "zoo_saturn.queue_mpmc_2.prefix" Tag1
)(in custom zoo_tag
).
Notation "'Used'" := (
  in_type "zoo_saturn.queue_mpmc_2.prefix" Tag2
)(in custom zoo_tag
).

Notation "'index'" := (
  in_type "zoo_saturn.queue_mpmc_2.prefix.Back" 0
)(in custom zoo_field
).
Notation "'move'" := (
  in_type "zoo_saturn.queue_mpmc_2.prefix.Back" 1
)(in custom zoo_field
).

Notation "'front'" := (
  in_type "zoo_saturn.queue_mpmc_2.t" 0
)(in custom zoo_field
).
Notation "'back'" := (
  in_type "zoo_saturn.queue_mpmc_2.t" 1
)(in custom zoo_field
).
