(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export backoff.backoff.
Require Export zoo_saturn.channel_sync_2.
Require Export zoo_saturn.stack_mpmc_1.
Require Export zoo_std.optional.
Require Import zoo.options.

Notation "'stack'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 0
)(in custom zoo_field
).
Notation "'channel'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 1
)(in custom zoo_field
).
Notation "'force_mutable'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 2
)(in custom zoo_field
).
