(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.stack_mpmc_3__code.

#[global] Opaque stack_mpmc_3٠capacity_log.
#[global] Opaque stack_mpmc_3٠create.
#[global] Opaque stack_mpmc_3٠try_push.
#[global] Opaque stack_mpmc_3٠push₁.
#[global] Opaque stack_mpmc_3٠push.
#[global] Opaque stack_mpmc_3٠try_pop.
#[global] Opaque stack_mpmc_3٠pop₁.
#[global] Opaque stack_mpmc_3٠pop.
