(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import backoff.backoff.
Require Import zoo_saturn.channel_sync_2.
Require Import zoo_saturn.stack_mpmc_1.
Require Import zoo_std.optional.
Require Import zoo.options.

Notation "'stack_mpmc_3٠stack'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 0
)(in custom zoo_field
).
Notation "'stack_mpmc_3٠channel'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 1
)(in custom zoo_field
).
Notation "'stack_mpmc_3٠force_mutable'" := (
  in_type "zoo_saturn.stack_mpmc_3.t" 2
)(in custom zoo_field
).

Definition stack_mpmc_3٠capacity_log : val :=
  3.

Definition stack_mpmc_3٠create : val :=
  𝗳𝘂𝗻 ⎽ ->
    { stack_mpmc_1٠create ()
    , channel_sync_2٠create stack_mpmc_3٠capacity_log
    , ()
    }.

Definition stack_mpmc_3٠try_push : val :=
  𝗳𝘂𝗻 "t" "v" ->
    stack_mpmc_1٠try_push "t".{stack_mpmc_3٠stack} "v"
    𝗼𝗿
    channel_sync_2٠send "t".{stack_mpmc_3٠channel} "v".

Definition stack_mpmc_3٠push₁ : val :=
  𝗿𝗲𝗰 "push" "t" "v" "backoff" ->
    𝗶𝗳 ~ stack_mpmc_3٠try_push "t" "v" 𝘁𝗵𝗲𝗻 (
      "push" "t" "v" (backoff٠once "backoff")
    ).

Definition stack_mpmc_3٠push : val :=
  𝗳𝘂𝗻 "t" "v" ->
    stack_mpmc_3٠push₁ "t" "v" backoff٠default.

Definition stack_mpmc_3٠try_pop : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 stack_mpmc_1٠try_pop "t".{stack_mpmc_3٠stack} 𝘄𝗶𝘁𝗵
    | optional٠Something ⎽ 𝗮𝘀 "res" ->
        "res"
    | optional٠Nothing ->
        §optional٠Nothing
    | optional٠Anything ->
        𝗺𝗮𝘁𝗰𝗵 channel_sync_2٠recv "t".{stack_mpmc_3٠channel} 𝘄𝗶𝘁𝗵
        | Some "v" ->
            ‘optional٠Something( "v" )
        | None ->
            §optional٠Anything
        𝗲𝗻𝗱
    𝗲𝗻𝗱.

Definition stack_mpmc_3٠pop₁ : val :=
  𝗿𝗲𝗰 "pop" "t" "backoff" ->
    𝗺𝗮𝘁𝗰𝗵 stack_mpmc_3٠try_pop "t" 𝘄𝗶𝘁𝗵
    | optional٠Nothing ->
        §None
    | optional٠Something "v" ->
        ‘Some( "v" )
    | optional٠Anything ->
        "pop" "t" (backoff٠once "backoff")
    𝗲𝗻𝗱.

Definition stack_mpmc_3٠pop : val :=
  𝗳𝘂𝗻 "t" ->
    stack_mpmc_3٠pop₁ "t" backoff٠default.
