(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.ws_bdeque_2__code.

#[global] Opaque ws_bdeque_2٠create.
#[global] Opaque ws_bdeque_2٠capacity.
#[global] Opaque ws_bdeque_2٠size.
#[global] Opaque ws_bdeque_2٠is_empty.
#[global] Opaque ws_bdeque_2٠push.
#[global] Opaque ws_bdeque_2٠steal.
#[global] Opaque ws_bdeque_2٠pop.
