(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.ws_deque_2__code.

#[global] Opaque ws_deque_2٠create.
#[global] Opaque ws_deque_2٠size.
#[global] Opaque ws_deque_2٠is_empty.
#[global] Opaque ws_deque_2٠push.
#[global] Opaque ws_deque_2٠steal.
#[global] Opaque ws_deque_2٠pop.
