(* This file was generated by ocaml2zoo. *)

Require Import zoo_saturn.ws_deque_1__code.

#[global] Opaque ws_deque_1٠min_capacity.
#[global] Opaque ws_deque_1٠create.
#[global] Opaque ws_deque_1٠size.
#[global] Opaque ws_deque_1٠is_empty.
#[global] Opaque ws_deque_1٠push.
#[global] Opaque ws_deque_1٠steal₁.
#[global] Opaque ws_deque_1٠steal.
#[global] Opaque ws_deque_1٠pop₁.
#[global] Opaque ws_deque_1٠pop.
