(env
 (_
  (rocq
   (flags
    (:standard
     -w +default
     -w -uniform-inheritance
     -w -redundant-canonical-projection
     -w -masking-absolute-name
     -w -notation-incompatible-prefix
     -w -notation-overridden
     -w -level-tolerance
     -w -missing-scheme
     -w -register-all
    )
   )
   (rocqdoc_flags
    (:standard
     --gallina
     --no-lib-name
     --external https://plv.mpi-sws.org/rocqdoc/stdpp/ stdpp
     --external https://plv.mpi-sws.org/rocqdoc/iris/ iris
     --external https://clef-men.github.io/doc/rocq-please/ please
    )
   )
  )
 )
)
