targets_norocq += lib
.PHONY : lib
lib :
	@ dune build @lib/check @lib/all

targets_norocq += ocaml2zoo
.PHONY : ocaml2zoo
ocaml2zoo :
	@ ocaml2zoo . theories

targets_norocq += bench
.PHONY : bench
bench :
	@ dune build bench

.PHONY : clean
clean ::
	@ dune clean
