ignore := zoo

targets_nocoq += lib
.PHONY : lib
lib :
	@ dune build @check @all

targets_nocoq += ocaml2zoo
.PHONY : ocaml2zoo
ocaml2zoo :
	@ ocaml2zoo $(addprefix --ignore ,$(ignore)) . theories

.PHONY : clean
clean ::
	@ dune clean
