(* This file was generated by ocaml2zoo. *)

Require Import zoo_data.parray__code.

#[global] Opaque parray٠make.
#[global] Opaque parray٠reroot₁.
#[global] Opaque parray٠reroot.
#[global] Opaque parray٠get.
#[global] Opaque parray٠set.
