(* This file was generated by ocaml2zoo. *)

Require Import zoo_data.pqueue__code.

#[global] Opaque pqueue٠empty.
#[global] Opaque pqueue٠is_empty.
#[global] Opaque pqueue٠push.
#[global] Opaque pqueue٠pop.
