(* This file was generated by ocaml2zoo. *)

Require Import zoo_data.pstack__code.

#[global] Opaque pstack٠empty.
#[global] Opaque pstack٠is_empty.
#[global] Opaque pstack٠push.
#[global] Opaque pstack٠pop.
