(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_data.sstore_2.
Require Import zoo.options.

Notation "'Root'" := (
  in_type "zoo_data.suf.descr" Tag0
)(in custom zoo_tag
).
Notation "'Link'" := (
  in_type "zoo_data.suf.descr" Tag1
)(in custom zoo_tag
).
