(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo.program_logic.identifier.
Require Export zoo_std.list.
Require Import zoo.options.

Notation "'casn'" := (
  in_type "zoo_mcas.mcas_2.state" 0
)(in custom zoo_field
).
Notation "'before'" := (
  in_type "zoo_mcas.mcas_2.state" 1
)(in custom zoo_field
).
Notation "'after'" := (
  in_type "zoo_mcas.mcas_2.state" 2
)(in custom zoo_field
).

Notation "'loc'" := (
  in_type "zoo_mcas.mcas_2.cas" 0
)(in custom zoo_proj
).
Notation "'state'" := (
  in_type "zoo_mcas.mcas_2.cas" 1
)(in custom zoo_proj
).

Notation "'status'" := (
  in_type "zoo_mcas.mcas_2.casn" 0
)(in custom zoo_field
).
Notation "'proph'" := (
  in_type "zoo_mcas.mcas_2.casn" 1
)(in custom zoo_field
).

Notation "'Undetermined'" := (
  in_type "zoo_mcas.mcas_2.status" Tag0
)(in custom zoo_tag
).
Notation "'Before'" := (
  in_type "zoo_mcas.mcas_2.status" Tag1
)(in custom zoo_tag
).
Notation "'After'" := (
  in_type "zoo_mcas.mcas_2.status" Tag2
)(in custom zoo_tag
).

Notation "'cmps'" := (
  in_type "zoo_mcas.mcas_2.status.Undetermined" 0
)(in custom zoo_proj
).
Notation "'cass'" := (
  in_type "zoo_mcas.mcas_2.status.Undetermined" 1
)(in custom zoo_proj
).
