(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_parabs.pool.
Require Import zoo_std.array.
Require Import zoo.options.

Definition pool_quicksort٠main₂ : val :=
  𝗿𝗲𝗰 "main" "ctx" "arr" "i" "sz" ->
    𝗶𝗳 1 < "sz" 𝘁𝗵𝗲𝗻 (
      𝗹𝗲𝘁 "pivot" = array٠partition "arr" "i" "sz" 𝗶𝗻
      pool٠async
        "ctx"
        (𝗳𝘂𝗻 "ctx" -> "main" "ctx" "arr" "i" ("pivot" - "i")) ⍮
      pool٠async
        "ctx"
        (𝗳𝘂𝗻 "ctx" ->
           "main" "ctx" "arr" ("pivot" + 1) ("sz" - ("pivot" - "i") - 1))
    ).

Definition pool_quicksort٠main₁ : val :=
  𝗳𝘂𝗻 "ctx" "arr" ->
    pool_quicksort٠main₂ "ctx" "arr" 0 (array٠size "arr").

Definition pool_quicksort٠main : val :=
  𝗳𝘂𝗻 "num_worker" "arr" ->
    pool٠run
      "num_worker"
      (𝗳𝘂𝗻 "ctx" -> pool_quicksort٠main₁ "ctx" "arr").
