From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclass_instances
  notations.
From zoo.tests Require Import
  basic_3__types.
From zoo Require Import
  options.

Definition basic_3_test1 : val :=
  fun: "x1" "x2" =>
    "x1" + "x2".

Definition basic_3_test2 : val :=
  fun: "x" <> =>
    "x".

Definition basic_3_test3_0 : val :=
  fun: "x1" "x2" "x3" =>
    "x1" + "x2" + "x3".

Definition basic_3_test3 : val :=
  fun: <> "x" <> =>
    "x".
