From zoo Require Import
  prelude.
From zoo.language Require Import
  notations.
From zoo.tests Require Import
  function__types.
From zoo Require Import
  options.

Definition function_test1 : val :=
  fun: "param" =>
    match: "param" with
    | Nil =>
        ()
    | Cons <> <> =>
        ()
    end.

Definition function_test2 : val :=
  rec: "test2" "param" =>
    match: "param" with
    | Nil =>
        ()
    | Cons <> <> =>
        ()
    end.
