From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclass_instances
  notations.
From zoo.tests Require Import
  if__types.
From zoo Require Import
  options.

Definition if_test1 : val :=
  fun: "b" =>
    if: "b" then (
      #0
    ) else (
      #1
    ).

Definition if_test2 : val :=
  fun: "b0" "b1" =>
    if: "b0" then (
      #0
    ) else if: "b1" then (
      #1
    ) else (
      #2
    ).

Definition if_test3 : val :=
  fun: "b0" "b1" "b2" =>
    if: "b0" then (
      #0
    ) else if: "b1" then (
      #1
    ) else if: "b2" then (
      #2
    ) else (
      #3
    ).

Definition if_test4 : val :=
  fun: "b" =>
    ifnot: "b" then (
      #0
    ) else (
      #1
    ).
