From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclass_instances
  notations.
From zoo.tests Require Import
  list__types.
From zoo Require Import
  options.

Definition list_test1 : val :=
  fun: <> =>
    [] ;;
    #0 :: [] ;;
    #1 :: [] ;;
    ().

Definition list_test2 : val :=
  fun: "xs" =>
    match: "xs" with
    | [] =>
        ()
    | "x" :: "xs" =>
        "x" ;;
        "xs" ;;
        ()
    end.
