From zoo Require Import
  prelude.
From zoo.language Require Import
  notations.
From zoo.tests Require Import
  match__types.
From zoo Require Import
  options.

Definition match_test1 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        #0
    | B "i" =>
        "i"
    | C "i1" "i2" =>
        "i1" + "i2"
    end.

Definition match_test2 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        ()
    | B <> =>
        ()
    | C <> <> =>
        ()
    end.

Definition match_test3 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        §A
    | B <> as "t" =>
        "t"
    | C <> <> as "t" =>
        "t"
    end.

Definition match_test4 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        ()
    |_ =>
        ()
    end.

Definition match_test5 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "t" =>
        "t"
    end.

Definition match_test6 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "t" =>
        let: "t'" := "t" in
        "t" ;;
        "t'"
    end.
