From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From zoo.tests Require Import
  operators_1__types.
From zoo Require Import
  options.

Definition operators_1_test1 : val :=
  fun: "i" =>
    ~ #true ;;
    - "i" ;;
    "i" + "i" ;;
    "i" - "i" ;;
    "i" * "i" ;;
    "i" `quot` "i" ;;
    "i" `rem` "i" ;;
    "i" == "i" ;;
    "i" != "i" ;;
    "i" ≤ "i" ;;
    "i" < "i" ;;
    "i" ≥ "i" ;;
    "i" > "i" ;;
    #2 * "i" + ("i" + #1) < "i" ;;
    #true and #true ;;
    #true or #true ;;
    #true and #true or #true ;;
    #true and (#true or #true) ;;
    #true or #true and #true ;;
    (#true or #true) and #true ;;
    ().

Definition operators_1_test2 : val :=
  fun: "i" =>
    (fun: "1" "2" => "1" + "2") ;;
    (fun: "1" "2" => "1" + "2") "i" ;;
    "i" + "i" ;;
    ().
