From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclass_instances
  notations.
From zoo.tests Require Import
  option__types.
From zoo Require Import
  options.

Definition option_test1 : val :=
  fun: <> =>
    §None ;;
    ‘Some( #0 ) ;;
    ().

Definition option_test2 : val :=
  fun: "o" =>
    match: "o" with
    | None =>
        #0
    | Some "i" =>
        "i"
    end.
