From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclass_instances
  notations.
From zoo Require Import
  diverge.
From zoo.tests Require Import
  raise_1__types.
From zoo Require Import
  options.

Definition raise_1_test1 : val :=
  fun: <> =>
    diverge ().

Definition raise_1_test2 : val :=
  fun: <> =>
    diverge ().

Definition raise_1_test3 : val :=
  fun: <> =>
    diverge ().
