From zoo Require Import
  prelude.
From zoo.language Require Import
  notations.
From zoo Require Import
  options.

Notation "'f1'" := (
  in_type "t1" 0
)(in custom zoo_field
).
Notation "'f2'" := (
  in_type "t1" 1
)(in custom zoo_field
).

Notation "'A'" := (
  in_type "t2" 0
)(in custom zoo_tag
).
Notation "'B'" := (
  in_type "t2" 1
)(in custom zoo_tag
).

Notation "'f'" := (
  in_type "t2__B" 0
)(in custom zoo_field
).
