(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_parabs.waiter.
Require Export zoo_saturn.queue_mpmc_1.
Require Export zoo_std.array.
Require Import zoo.options.

Notation "'waiters'" := (
  in_type "zoo_parabs.waiters.t" 0
)(in custom zoo_proj
).
Notation "'queue'" := (
  in_type "zoo_parabs.waiters.t" 1
)(in custom zoo_proj
).
