(* This file was generated by ocaml2zoo. *)

Require Import zoo_parabs.ws_deques_public__code.

#[global] Opaque ws_deques_public٠create.
#[global] Opaque ws_deques_public٠size.
#[global] Opaque ws_deques_public٠block.
#[global] Opaque ws_deques_public٠unblock.
#[global] Opaque ws_deques_public٠push.
#[global] Opaque ws_deques_public٠pop.
#[global] Opaque ws_deques_public٠steal_to.
#[global] Opaque ws_deques_public٠steal_as₁.
#[global] Opaque ws_deques_public٠steal_as.
