(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_parabs.waiters.
Require Export zoo_parabs.ws_deques_public.
Require Export zoo_std.array.
Require Export zoo_std.domain.
Require Export zoo_std.int.
Require Export zoo_std.optional.
Require Export zoo_std.random_round.
Require Import zoo.options.

Notation "'deques'" := (
  in_type "zoo_parabs.ws_hub_std.t" 0
)(in custom zoo_field
).
Notation "'rounds'" := (
  in_type "zoo_parabs.ws_hub_std.t" 1
)(in custom zoo_field
).
Notation "'waiters'" := (
  in_type "zoo_parabs.ws_hub_std.t" 2
)(in custom zoo_field
).
Notation "'num_active'" := (
  in_type "zoo_parabs.ws_hub_std.t" 3
)(in custom zoo_field
).
