From zoo_std Require Import
  array__code.

#[global] Opaque array٠unsafe_alloc.
#[global] Opaque array٠alloc.
#[global] Opaque array٠create.
#[global] Opaque array٠size.
#[global] Opaque array٠unsafe_get.
#[global] Opaque array٠get.
#[global] Opaque array٠unsafe_set.
#[global] Opaque array٠set.
#[global] Opaque array٠unsafe_swap.
#[global] Opaque array٠unsafe_fill_slice.
#[global] Opaque array٠fill_slice.
#[global] Opaque array٠fill.
#[global] Opaque array٠unsafe_make.
#[global] Opaque array٠make.
#[global] Opaque array٠foldli.
#[global] Opaque array٠foldl.
#[global] Opaque array٠sum.
#[global] Opaque array٠foldri.
#[global] Opaque array٠foldr.
#[global] Opaque array٠unsafe_iteri_slice.
#[global] Opaque array٠iteri_slice.
#[global] Opaque array٠unsafe_iter_slice.
#[global] Opaque array٠iter_slice.
#[global] Opaque array٠iteri.
#[global] Opaque array٠iter.
#[global] Opaque array٠unsafe_applyi_slice.
#[global] Opaque array٠applyi_slice.
#[global] Opaque array٠unsafe_apply_slice.
#[global] Opaque array٠apply_slice.
#[global] Opaque array٠applyi.
#[global] Opaque array٠apply.
#[global] Opaque array٠unsafe_initi.
#[global] Opaque array٠initi.
#[global] Opaque array٠unsafe_init.
#[global] Opaque array٠init.
#[global] Opaque array٠mapi.
#[global] Opaque array٠map.
#[global] Opaque array٠unsafe_copy_slice.
#[global] Opaque array٠copy_slice.
#[global] Opaque array٠unsafe_copy.
#[global] Opaque array٠copy.
#[global] Opaque array٠unsafe_grow.
#[global] Opaque array٠grow.
#[global] Opaque array٠unsafe_sub.
#[global] Opaque array٠sub.
#[global] Opaque array٠unsafe_shrink.
#[global] Opaque array٠shrink.
#[global] Opaque array٠clone.
#[global] Opaque array٠unsafe_cget.
#[global] Opaque array٠cget.
#[global] Opaque array٠unsafe_cset.
#[global] Opaque array٠cset.
#[global] Opaque array٠unsafe_ccopy_slice.
#[global] Opaque array٠ccopy_slice.
#[global] Opaque array٠unsafe_ccopy.
#[global] Opaque array٠ccopy.
#[global] Opaque array٠unsafe_cgrow_slice.
#[global] Opaque array٠unsafe_cgrow.
#[global] Opaque array٠unsafe_cshrink_slice.
