From zoo_std Require Import
  array__code.

#[global] Opaque array_unsafe_alloc.
#[global] Opaque array_alloc.
#[global] Opaque array_create.
#[global] Opaque array_size.
#[global] Opaque array_unsafe_get.
#[global] Opaque array_get.
#[global] Opaque array_unsafe_set.
#[global] Opaque array_set.
#[global] Opaque array_unsafe_fill_slice.
#[global] Opaque array_fill_slice.
#[global] Opaque array_fill.
#[global] Opaque array_unsafe_make.
#[global] Opaque array_make.
#[global] Opaque array_foldli.
#[global] Opaque array_foldl.
#[global] Opaque array_sum.
#[global] Opaque array_foldri.
#[global] Opaque array_foldr.
#[global] Opaque array_unsafe_iteri_slice.
#[global] Opaque array_iteri_slice.
#[global] Opaque array_unsafe_iter_slice.
#[global] Opaque array_iter_slice.
#[global] Opaque array_iteri.
#[global] Opaque array_iter.
#[global] Opaque array_unsafe_applyi_slice.
#[global] Opaque array_applyi_slice.
#[global] Opaque array_unsafe_apply_slice.
#[global] Opaque array_apply_slice.
#[global] Opaque array_applyi.
#[global] Opaque array_apply.
#[global] Opaque array_unsafe_initi.
#[global] Opaque array_initi.
#[global] Opaque array_unsafe_init.
#[global] Opaque array_init.
#[global] Opaque array_mapi.
#[global] Opaque array_map.
#[global] Opaque array_unsafe_copy_slice.
#[global] Opaque array_copy_slice.
#[global] Opaque array_unsafe_copy.
#[global] Opaque array_copy.
#[global] Opaque array_unsafe_grow.
#[global] Opaque array_grow.
#[global] Opaque array_unsafe_sub.
#[global] Opaque array_sub.
#[global] Opaque array_unsafe_shrink.
#[global] Opaque array_shrink.
#[global] Opaque array_clone.
#[global] Opaque array_unsafe_cget.
#[global] Opaque array_cget.
#[global] Opaque array_unsafe_cset.
#[global] Opaque array_cset.
#[global] Opaque array_unsafe_ccopy_slice.
#[global] Opaque array_ccopy_slice.
#[global] Opaque array_unsafe_ccopy.
#[global] Opaque array_ccopy.
#[global] Opaque array_unsafe_cgrow_slice.
#[global] Opaque array_unsafe_cgrow.
#[global] Opaque array_unsafe_cshrink_slice.
