(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.bqueue__code.

#[global] Opaque bqueue٠create.
#[global] Opaque bqueue٠size.
#[global] Opaque bqueue٠is_empty.
#[global] Opaque bqueue٠unsafe_get.
#[global] Opaque bqueue٠unsafe_set.
#[global] Opaque bqueue٠push.
#[global] Opaque bqueue٠pop_front.
#[global] Opaque bqueue٠pop_back.
