(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'chain٠next'" := (
  in_type "zoo_std.chain.t" 0
)(in custom zoo_field
).
Notation "'chain٠data'" := (
  in_type "zoo_std.chain.t" 1
)(in custom zoo_field
).
