(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'Closed'" := (
  in_type "zoo_std.clist.t" Tag0
)(in custom zoo_tag
).
Notation "'Open'" := (
  in_type "zoo_std.clist.t" Tag1
)(in custom zoo_tag
).
Notation "'Cons'" := (
  in_type "zoo_std.clist.t" Tag2
)(in custom zoo_tag
).
