(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.deque__code.

#[global] Opaque deque٠create.
#[global] Opaque deque٠is_empty.
#[global] Opaque deque٠push_front.
#[global] Opaque deque٠push_back.
#[global] Opaque deque٠pop_front.
#[global] Opaque deque٠pop_back.
#[global] Opaque deque٠iter.
