(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.dynarray_1__code.

#[global] Opaque dynarray_1٠create.
#[global] Opaque dynarray_1٠make.
#[global] Opaque dynarray_1٠initi.
#[global] Opaque dynarray_1٠size.
#[global] Opaque dynarray_1٠capacity.
#[global] Opaque dynarray_1٠is_empty.
#[global] Opaque dynarray_1٠get.
#[global] Opaque dynarray_1٠set.
#[global] Opaque dynarray_1٠next_capacity.
#[global] Opaque dynarray_1٠reserve.
#[global] Opaque dynarray_1٠reserve_extra.
#[global] Opaque dynarray_1٠grow.
#[global] Opaque dynarray_1٠push.
#[global] Opaque dynarray_1٠pop.
#[global] Opaque dynarray_1٠fit_capacity.
#[global] Opaque dynarray_1٠reset.
#[global] Opaque dynarray_1٠iteri.
#[global] Opaque dynarray_1٠iter.
