(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.dynarray_2__code.

#[global] Opaque dynarray_2٠element.
#[global] Opaque dynarray_2٠create.
#[global] Opaque dynarray_2٠make.
#[global] Opaque dynarray_2٠initi.
#[global] Opaque dynarray_2٠size.
#[global] Opaque dynarray_2٠data.
#[global] Opaque dynarray_2٠capacity.
#[global] Opaque dynarray_2٠set_size.
#[global] Opaque dynarray_2٠set_data.
#[global] Opaque dynarray_2٠is_empty.
#[global] Opaque dynarray_2٠get.
#[global] Opaque dynarray_2٠set.
#[global] Opaque dynarray_2٠next_capacity.
#[global] Opaque dynarray_2٠reserve.
#[global] Opaque dynarray_2٠reserve_extra.
#[global] Opaque dynarray_2٠try_grow.
#[global] Opaque dynarray_2٠grow₁.
#[global] Opaque dynarray_2٠grow.
#[global] Opaque dynarray_2٠try_push.
#[global] Opaque dynarray_2٠push₁.
#[global] Opaque dynarray_2٠push.
#[global] Opaque dynarray_2٠pop.
#[global] Opaque dynarray_2٠fit_capacity.
#[global] Opaque dynarray_2٠reset.
#[global] Opaque dynarray_2٠iteri.
#[global] Opaque dynarray_2٠iter.
