(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.inf_array__code.

#[global] Opaque inf_array٠create.
#[global] Opaque inf_array٠next_capacity.
#[global] Opaque inf_array٠reserve.
#[global] Opaque inf_array٠get.
#[global] Opaque inf_array٠update.
#[global] Opaque inf_array٠xchg.
#[global] Opaque inf_array٠xchg_resolve.
#[global] Opaque inf_array٠set.
#[global] Opaque inf_array٠cas.
#[global] Opaque inf_array٠cas_resolve.
#[global] Opaque inf_array٠faa.
