(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.ivar_4__code.

#[global] Opaque ivar_4٠create.
#[global] Opaque ivar_4٠make.
#[global] Opaque ivar_4٠is_unset.
#[global] Opaque ivar_4٠is_set.
#[global] Opaque ivar_4٠try_get.
#[global] Opaque ivar_4٠get.
#[global] Opaque ivar_4٠wait.
#[global] Opaque ivar_4٠set.
#[global] Opaque ivar_4٠notify.
