(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.ivar_1__code.

#[global] Opaque ivar_1٠create.
#[global] Opaque ivar_1٠make.
#[global] Opaque ivar_1٠try_get.
#[global] Opaque ivar_1٠is_unset.
#[global] Opaque ivar_1٠is_set.
#[global] Opaque ivar_1٠get.
#[global] Opaque ivar_1٠set.
