(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.ivar_3__code.

#[global] Opaque ivar_3٠create.
#[global] Opaque ivar_3٠make.
#[global] Opaque ivar_3٠is_unset.
#[global] Opaque ivar_3٠is_set.
#[global] Opaque ivar_3٠try_get.
#[global] Opaque ivar_3٠get.
#[global] Opaque ivar_3٠wait.
#[global] Opaque ivar_3٠set.
