(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'ivar_3٠Unset'" := (
  in_type "zoo_std.ivar_3.state" Tag0
)(in custom zoo_tag
).
Notation "'ivar_3٠Set'" := (
  in_type "zoo_std.ivar_3.state" Tag1
)(in custom zoo_tag
).

Definition ivar_3٠create : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗿𝗲𝗳 ‘ivar_3٠Unset[ [] ].

Definition ivar_3٠make : val :=
  𝗳𝘂𝗻 "v" ->
    𝗿𝗲𝗳 ‘ivar_3٠Set( "v" ).

Definition ivar_3٠is_unset : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
    | ivar_3٠Unset ⎽ ->
        true
    | ivar_3٠Set ⎽ ->
        false
    𝗲𝗻𝗱.

Definition ivar_3٠is_set : val :=
  𝗳𝘂𝗻 "t" ->
    ~ ivar_3٠is_unset "t".

Definition ivar_3٠try_get : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
    | ivar_3٠Unset ⎽ ->
        §None
    | ivar_3٠Set "v" ->
        ‘Some( "v" )
    𝗲𝗻𝗱.

Definition ivar_3٠get : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
    | ivar_3٠Unset ⎽ ->
        𝗳𝗮𝗶𝗹
    | ivar_3٠Set "v" ->
        "v"
    𝗲𝗻𝗱.

Definition ivar_3٠wait : val :=
  𝗿𝗲𝗰 "wait" "t" "waiter" ->
    𝗺𝗮𝘁𝗰𝗵 !"t" 𝘄𝗶𝘁𝗵
    | ivar_3٠Unset "waiters" 𝗮𝘀 "state" ->
        𝗶𝗳
          𝗰𝗮𝘀
            "t".[contents]
            "state"
            ‘ivar_3٠Unset[ "waiter" :: "waiters" ]
        𝘁𝗵𝗲𝗻 (
          §None
        ) 𝗲𝗹𝘀𝗲 (
          "wait" "t" "waiter"
        )
    | ivar_3٠Set "v" ->
        ‘Some( "v" )
    𝗲𝗻𝗱.

Definition ivar_3٠set : val :=
  𝗳𝘂𝗻 "t" "v" ->
    𝗺𝗮𝘁𝗰𝗵
      𝘅𝗰𝗵𝗴 "t".[contents] ‘ivar_3٠Set( "v" )
    𝘄𝗶𝘁𝗵
    | ivar_3٠Set ⎽ ->
        𝗳𝗮𝗶𝗹
    | ivar_3٠Unset "waiters" ->
        "waiters"
    𝗲𝗻𝗱.
