(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_std.condition.
Require Import zoo_std.mutex.
Require Import zoo.options.

Notation "'latch٠counter'" := (
  in_type "zoo_std.latch.t" 0
)(in custom zoo_field
).
Notation "'latch٠mutex'" := (
  in_type "zoo_std.latch.t" 1
)(in custom zoo_field
).
Notation "'latch٠condition'" := (
  in_type "zoo_std.latch.t" 2
)(in custom zoo_field
).

Definition latch٠create : val :=
  𝗳𝘂𝗻 "sz" ->
    { "sz", mutex٠create (), condition٠create () }.

Definition latch٠wait : val :=
  𝗳𝘂𝗻 "t" ->
    mutex٠protect "t".{latch٠mutex}
      (𝗳𝘂𝗻 ⎽ ->
         "t" <-{latch٠counter} "t".{latch٠counter} - 1 ⍮
         condition٠wait_until "t".{latch٠condition} "t".{latch٠mutex}
           (𝗳𝘂𝗻 ⎽ -> "t".{latch٠counter} == 0)).
