(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.lazy__code.

#[global] Opaque lazy٠make.
#[global] Opaque lazy٠return.
#[global] Opaque lazy٠is_set.
#[global] Opaque lazy٠is_unset.
#[global] Opaque lazy٠get.
