(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export zoo_std.mutex.
Require Import zoo.options.

Notation "'Unset'" := (
  in_type "zoo_std.lazy.state" Tag0
)(in custom zoo_tag
).
Notation "'Setting'" := (
  in_type "zoo_std.lazy.state" Tag1
)(in custom zoo_tag
).
Notation "'Set'" := (
  in_type "zoo_std.lazy.state" Tag2
)(in custom zoo_tag
).
