Require Import zoo_std.list__code.

#[global] Opaque list٠singleton.
#[global] Opaque list٠head.
#[global] Opaque list٠tail.
#[global] Opaque list٠is_empty.
#[global] Opaque list٠get.
#[global] Opaque list٠initi₁.
#[global] Opaque list٠initi.
#[global] Opaque list٠init.
#[global] Opaque list٠foldli₁.
#[global] Opaque list٠foldli.
#[global] Opaque list٠foldl.
#[global] Opaque list٠foldri₁.
#[global] Opaque list٠foldri.
#[global] Opaque list٠foldr.
#[global] Opaque list٠size.
#[global] Opaque list٠rev_app.
#[global] Opaque list٠rev.
#[global] Opaque list٠app.
#[global] Opaque list٠snoc.
#[global] Opaque list٠iteri.
#[global] Opaque list٠iter.
#[global] Opaque list٠mapi₁.
#[global] Opaque list٠mapi.
#[global] Opaque list٠map.
#[global] Opaque list٠forall.
#[global] Opaque list٠exists.
