(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'Nothing'" := (
  in_type "zoo_std.optional.t" Tag0
)(in custom zoo_tag
).
Notation "'Anything'" := (
  in_type "zoo_std.optional.t" Tag1
)(in custom zoo_tag
).
Notation "'Something'" := (
  in_type "zoo_std.optional.t" Tag2
)(in custom zoo_tag
).
