(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.queue_3__code.

#[global] Opaque queue_3٠min_capacity.
#[global] Opaque queue_3٠create.
#[global] Opaque queue_3٠size.
#[global] Opaque queue_3٠is_empty.
#[global] Opaque queue_3٠unsafe_get.
#[global] Opaque queue_3٠unsafe_set.
#[global] Opaque queue_3٠next_capacity.
#[global] Opaque queue_3٠grow.
#[global] Opaque queue_3٠push.
#[global] Opaque queue_3٠shrink.
#[global] Opaque queue_3٠pop_front.
#[global] Opaque queue_3٠pop_back.
