(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.random_round__code.

#[global] Opaque random_round٠create.
#[global] Opaque random_round٠reset.
#[global] Opaque random_round٠next.
