(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.random__code.

#[global] Opaque random٠init.
#[global] Opaque random٠bits.
#[global] Opaque random٠int.
#[global] Opaque random٠int_in_range.
