(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo_std.array.
Require Import zoo_std.random_state.
Require Import zoo.options.

Notation "'random_round٠random'" := (
  in_type "zoo_std.random_round.t" 0
)(in custom zoo_field
).
Notation "'random_round٠array'" := (
  in_type "zoo_std.random_round.t" 1
)(in custom zoo_field
).
Notation "'random_round٠index'" := (
  in_type "zoo_std.random_round.t" 2
)(in custom zoo_field
).

Definition random_round٠create : val :=
  𝗳𝘂𝗻 "sz" ->
    { random_state٠create (),
      array٠unsafe_initi "sz" (𝗳𝘂𝗻 "i" -> "i"),
      "sz"
    }.

Definition random_round٠reset : val :=
  𝗳𝘂𝗻 "t" ->
    "t" <-{random_round٠index} array٠size "t".{random_round٠array}.

Definition random_round٠next : val :=
  𝗳𝘂𝗻 "t" ->
    𝗹𝗲𝘁 "arr" = "t".{random_round٠array} 𝗶𝗻
    𝗹𝗲𝘁 "i" = "t".{random_round٠index} 𝗶𝗻
    𝗹𝗲𝘁 "j" =
      random_state٠int "t".{random_round٠random} "i"
    𝗶𝗻
    𝗹𝗲𝘁 "res" = array٠unsafe_get "arr" "j" 𝗶𝗻
    𝗹𝗲𝘁 "i" = "i" - 1 𝗶𝗻
    array٠unsafe_set "arr" "j" (array٠unsafe_get "arr" "i") ⍮
    array٠unsafe_set "arr" "i" "res" ⍮
    "t" <-{random_round٠index} "i" ⍮
    "res".
