(* This file was generated by ocaml2zoo. *)

Require Import zoo_std.stack__code.

#[global] Opaque stack٠create.
#[global] Opaque stack٠is_empty.
#[global] Opaque stack٠push.
#[global] Opaque stack٠pop.
