(* This file was generated by ocaml2zoo. *)

Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Export unix.unix.
Require Export zoo_std.waiter_spsc.
Require Import zoo.options.

Notation "'Open'" := (
  in_type "zoo_eio.rcfd.state" Tag0
)(in custom zoo_tag
).
Notation "'Closing'" := (
  in_type "zoo_eio.rcfd.state" Tag1
)(in custom zoo_tag
).

Notation "'ops'" := (
  in_type "zoo_eio.rcfd.t" 0
)(in custom zoo_field
).
Notation "'state'" := (
  in_type "zoo_eio.rcfd.t" 1
)(in custom zoo_field
).
