(* This file was generated by ocaml2zoo. *)

Require Import zoo_persistent.sstore_1__code.

#[global] Opaque sstore_1٠create.
#[global] Opaque sstore_1٠ref.
#[global] Opaque sstore_1٠get.
#[global] Opaque sstore_1٠set.
#[global] Opaque sstore_1٠capture.
#[global] Opaque sstore_1٠collect.
#[global] Opaque sstore_1٠revert.
#[global] Opaque sstore_1٠reroot.
#[global] Opaque sstore_1٠restore.
