(* This file was generated by ocaml2zoo. *)

Require Import zoo_persistent.sstore_2__code.

#[global] Opaque sstore_2٠create.
#[global] Opaque sstore_2٠ref.
#[global] Opaque sstore_2٠get.
#[global] Opaque sstore_2٠set.
#[global] Opaque sstore_2٠capture.
#[global] Opaque sstore_2٠collect.
#[global] Opaque sstore_2٠revert.
#[global] Opaque sstore_2٠reroot.
#[global] Opaque sstore_2٠restore.
